### PR TITLE
template draft

### PR DESCRIPTION
**Pull request by isaacvando**
Here's my first draft of the HTML template engine. It is already quite nice to use which I am very happy about. I will start a related topic on Zulip about how we should do parsing in the book. Cheers! @gvwilson

### CODE REVIEW

**Comment by gvwilson** [comment]
This looks great to me - I'm assuming that every project is going to need to add a few things of its own to its own `.gitignore` (so we can't promote that to the top level)?

**Comment by isaacvando** [comment]
@gvwilson Great! We could move the gitignore to the top level; it doesn't matter to me. I will send a message in Zulip about feedback and if there is none by tomorrow you can merge it then. We can always have more feedback down the line also.

**Comment by isaacvando** [comment]
Related to #5

**Comment by Anton-4** [comment]
Looks nice and clean :)

**Comment by isaacvando** [comment]
@gvwilson This is ready to merge when you get a chance. Thanks!

**Pull request merged**
